# check [link](https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages)

name: NPM Publish

on:
  push:
    tags: [v*]
#  release:
#    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
#      - run: npm ci
#      - run: npm test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
